name: Reporter
version: 0.1
author: rfsantos1996
main: com.jabyftw.reporter.Reporter
description: Report griefers!
commands:
   report:
     description: Main command
     permission: reporter.report
     usage: Use /report help
permissions:
   reporter.report:
     description: Gives access to a Reporter command
     default: true
   reporter.report.info:
     description: Gives access to a Reporter command
     default: op
   reporter.report.list:
     description: Gives access to a Reporter command
     default: op
   reporter.report.close:
     description: Gives access to a Reporter command
     default: op
   reporter.report.reopen:
     description: Gives access to a Reporter command
     default: op