name: Reporter
version: 1.0.1
author: rfsantos1996
main: com.jabyftw.reporter.Reporter
description: Report griefers!
softdepend: [Notifications]
commands:
   report:
     description: Main PLAYER command
     permission: reporter.report
     usage: Use /report help
   reporter:
     description: Main ADMIN command
     permission: reporter.reporter
     usage: Use /report help
permissions:
   reporter.report:
     description: Gives access to a Reporter command
     default: true
   reporter.report.info:
     description: Gives access to a Reporter command
     default: true
   reporter.report.info.others:
     description: Gives access to a Reporter command
     default: op
   reporter.report.notify:
     description: Gives access to a Reporter command
     default: op
   reporter.list:
     description: Gives access to a Reporter command
     default: op
   reporter.close:
     description: Gives access to a Reporter command
     default: op
   reporter.reopen:
     description: Gives access to a Reporter command
     default: op
   reporter.tp:
     description: Gives access to a Reporter command
     default: op